name: 
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - _x86_64-microarch-level=3
  - adwaita-icon-theme=48.1
  - annotated-types=0.7.0
  - anyio=4.10.0
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - at-spi2-atk=2.38.0
  - at-spi2-core=2.40.3
  - atk-1.0=2.38.0
  - attrs=25.3.0
  - awkward=2.8.9
  - awkward-cpp=50
  - babel=2.17.0
  - beautifulsoup4=4.13.5
  - binutils=2.44
  - binutils_impl_linux-64=2.44
  - binutils_linux-64=2.44
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - c-compiler=1.11.0
  - ca-certificates=2025.8.3
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2025.8.3
  - cffi=1.17.1
  - cfitsio=4.6.2
  - charset-normalizer=3.4.3
  - click=8.3.0
  - colorama=0.4.6
  - comm=0.2.3
  - compilers=1.11.0
  - conda-gcc-specs=14.3.0
  - contourpy=1.3.3
  - cpython=3.13.7
  - cxx-compiler=1.11.0
  - cycler=0.12.1
  - davix=0.8.10
  - dbus=1.16.2
  - debugpy=1.8.17
  - decorator=5.2.1
  - defusedxml=0.7.1
  - epoxy=1.5.10
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - fastjet-cxx=3.4.3
  - fftw=3.3.10
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.0
  - fortran-compiler=1.11.0
  - fqdn=1.5.1
  - freetype=2.14.1
  - fribidi=1.0.16
  - fsspec=2025.9.0
  - ftgl=2.4.0
  - gcc=14.3.0
  - gcc_impl_linux-64=14.3.0
  - gcc_linux-64=14.3.0
  - gdk-pixbuf=2.44.1
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - gfortran=14.3.0
  - gfortran_impl_linux-64=14.3.0
  - gfortran_linux-64=14.3.0
  - giflib=5.2.2
  - gl2ps=1.4.2
  - glew=2.1.0
  - glib-tools=2.86.0
  - graphite2=1.3.14
  - graphviz=13.1.2
  - gsl=2.7
  - gsoap=2.8.123
  - gtest=1.16.0
  - gtk3=3.24.43
  - gts=0.7.6
  - gxx=14.3.0
  - gxx_impl_linux-64=14.3.0
  - gxx_linux-64=14.3.0
  - h11=0.16.0
  - h2=4.3.0
  - harfbuzz=11.5.0
  - hicolor-icon-theme=0.17
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipyparallel=9.0.1
  - ipython=9.5.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter=1.1.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.7
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lark=1.2.2
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcups=2.3.3
  - libcurl=8.14.1
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.1.0
  - libgcc-devel_linux-64=14.3.0
  - libgcc-ng=15.1.0
  - libgd=2.3.3
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.86.0
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libllvm18=18.1.8
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libnghttp2=1.67.0
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libpng=1.6.50
  - librsvg=2.58.4
  - libsanitizer=14.3.0
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-devel_linux-64=14.3.0
  - libstdcxx-ng=15.1.0
  - libtiff=4.7.1
  - libuuid=2.41.1
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.11.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - llvm-openmp=21.1.0
  - llvmlite=0.44.0
  - lz4-c=1.10.0
  - markdown-it-py=4.0.0
  - markupsafe=3.0.2
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - metakernel=0.30.3
  - mistune=3.1.4
  - mplhep=0.4.1
  - mplhep_data=0.0.4
  - munkres=1.1.4
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nlohmann_json=3.12.0
  - nodeenv=1.9.1
  - nodejs=24.8.0
  - notebook=7.4.5
  - notebook-shim=0.2.4
  - numba=0.61.2
  - numpy=2.2.6
  - openjpeg=2.5.4
  - openssl=3.5.3
  - overrides=7.7.0
  - packaging=25.0
  - pandocfilters=1.5.0
  - pango=1.56.4
  - parallel=20250822
  - parso=0.8.5
  - pcre=8.45
  - pcre2=10.46
  - perl=5.32.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.4.0
  - portalocker=3.2.0
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - psutil=7.1.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pydantic=2.11.9
  - pydantic-core=2.33.2
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pyright=1.1.405
  - pysocks=1.7.1
  - pythia8=8.312
  - python=3.13.7
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-gil=3.13.7
  - python-json-logger=2.0.7
  - python_abi=3.13
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=27.1.0
  - qhull=2020.2
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rich=14.1.0
  - root=6.36.04
  - root_base=6.36.04
  - rpds-py=0.27.1
  - scitokens-cpp=1.1.3
  - send2trash=1.8.3
  - setuptools=80.9.0
  - shellingham=1.5.4
  - siscone=3.0.6
  - six=1.17.0
  - sniffio=1.3.1
  - soupsieve=2.8
  - stack_data=0.6.3
  - sysroot_linux-64=2.17
  - tbb=2022.2.0
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.2.1
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typer=0.19.1
  - typer-slim=0.19.1
  - typer-slim-standard=0.19.1
  - types-python-dateutil=2.9.0.20250822
  - typing-extensions=4.15.0
  - typing-inspection=0.4.1
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - uhi=1.0.0
  - uri-template=1.3.0
  - urllib3=2.5.0
  - vdt=0.4.4
  - vector=1.6.3
  - vector-classes=1.4.5
  - wayland=1.24.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - widgetsnbextension=4.0.14
  - xkeyboard-config=2.45
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxft=2.3.9
  - xorg-libxi=1.8.2
  - xorg-libxinerama=1.1.5
  - xorg-libxpm=3.5.17
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - xorg-libxtst=1.2.5
  - xorg-xorgproto=2024.1
  - xrootd=5.8.4
  - xxhash=0.8.3
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.25.0
  - zstd=1.5.7

